'use strict';

const FLOWS = {
  IDLE: 'IDLE',
  REGISTRATION: 'REGISTRATION',
  MAIN_MENU: 'MAIN_MENU',
  OFFER_RIDE: 'OFFER_RIDE',
  FIND_RIDE: 'FIND_RIDE',
  VIEW_RESULTS: 'VIEW_RESULTS',
  BOOKING: 'BOOKING',
  RECURRING: 'RECURRING',
  MY_BOOKINGS: 'MY_BOOKINGS',
  CANCEL_BOOKING: 'CANCEL_BOOKING',
  RATING: 'RATING',
};

const STEPS = {
  // Registration (5 steps, no OTP)
  REG_ASK_NAME: 'REG_ASK_NAME',
  REG_ASK_GENDER: 'REG_ASK_GENDER',
  REG_ASK_HOME: 'REG_ASK_HOME',
  REG_ASK_OFFICE: 'REG_ASK_OFFICE',
  REG_ASK_VEHICLE: 'REG_ASK_VEHICLE',

  // Main menu
  MENU_AWAITING: 'MENU_AWAITING',

  // Offer ride
  OFFER_ASK_PICKUP: 'OFFER_ASK_PICKUP',
  OFFER_ASK_DEST: 'OFFER_ASK_DEST',
  OFFER_ASK_TIME: 'OFFER_ASK_TIME',
  OFFER_ASK_SEATS: 'OFFER_ASK_SEATS',
  OFFER_ASK_PRICE: 'OFFER_ASK_PRICE',
  OFFER_ASK_VEHICLE: 'OFFER_ASK_VEHICLE',
  OFFER_ASK_PREFERENCE: 'OFFER_ASK_PREFERENCE',
  OFFER_CONFIRM: 'OFFER_CONFIRM',

  // Find ride
  FIND_ASK_PICKUP: 'FIND_ASK_PICKUP',
  FIND_ASK_DEST: 'FIND_ASK_DEST',
  FIND_ASK_TIME: 'FIND_ASK_TIME',
  FIND_ASK_SEATS: 'FIND_ASK_SEATS',
  FIND_ASK_PREFERENCE: 'FIND_ASK_PREFERENCE',

  // View results
  RESULTS_SHOW: 'RESULTS_SHOW',

  // Booking
  BOOK_CONFIRM: 'BOOK_CONFIRM',

  // Recurring
  RECURRING_ASK: 'RECURRING_ASK',

  // Cancel
  CANCEL_SELECT: 'CANCEL_SELECT',
  CANCEL_CONFIRM: 'CANCEL_CONFIRM',

  // Rating
  RATING_ASK: 'RATING_ASK',
  RATING_FEEDBACK: 'RATING_FEEDBACK',
};

const RIDE_PREFERENCE = {
  ALL: 'all',
  WOMEN_ONLY: 'women_only',
};

const GENDER = {
  MALE: 'Male',
  FEMALE: 'Female',
  OTHER: 'Other',
};

const VEHICLE_TYPES = ['car', 'bike', 'auto'];

const RIDE_STATUS = {
  ACTIVE: 'active',
  FULL: 'full',
  CANCELLED: 'cancelled',
  COMPLETED: 'completed',
};

const BOOKING_STATUS = {
  CONFIRMED: 'confirmed',
  CANCELLED: 'cancelled',
};

const RESULTS_PAGE_SIZE = 3;
const SESSION_TTL_MS = 30 * 60 * 1000;
const MAX_PICKUP_RADIUS_KM = 3.0;
const MAX_TIME_DIFF_MINUTES = 30;

module.exports = {
  FLOWS, STEPS, RIDE_PREFERENCE, GENDER,
  VEHICLE_TYPES, RIDE_STATUS, BOOKING_STATUS,
  RESULTS_PAGE_SIZE, SESSION_TTL_MS,
  MAX_PICKUP_RADIUS_KM, MAX_TIME_DIFF_MINUTES,
};
