'use strict';

const FLOWS = {
  IDLE: 'IDLE',
  REGISTRATION: 'REGISTRATION',
  MAIN_MENU: 'MAIN_MENU',
  OFFER_RIDE: 'OFFER_RIDE',
  FIND_RIDE: 'FIND_RIDE',
  VIEW_RESULTS: 'VIEW_RESULTS',
  BOOKING: 'BOOKING',
  RECURRING: 'RECURRING',
  MY_BOOKINGS: 'MY_BOOKINGS',
  CANCEL_BOOKING: 'CANCEL_BOOKING',
  RATING: 'RATING',
  ACTIVE_RIDE: 'ACTIVE_RIDE',
  POST_TRIP: 'POST_TRIP',
  FEEDBACK: 'FEEDBACK',
};

const STEPS = {
  // Registration (1 step)
  REG_ASK_NAME: 'REG_ASK_NAME',

  // Main menu
  MENU_AWAITING: 'MENU_AWAITING',

  // Offer ride
  OFFER_ASK_REPEAT:      'OFFER_ASK_REPEAT',
  OFFER_ASK_PICKUP_LOC:  'OFFER_ASK_PICKUP_LOC',
  OFFER_ASK_DEST_LOC:    'OFFER_ASK_DEST_LOC',
  OFFER_ASK_TIME:        'OFFER_ASK_TIME',
  OFFER_ASK_SEATS:       'OFFER_ASK_SEATS',
  OFFER_ASK_VEHICLE:     'OFFER_ASK_VEHICLE',
  OFFER_ASK_PREFERENCE:  'OFFER_ASK_PREFERENCE',
  OFFER_ASK_VEHICLE_NUM: 'OFFER_ASK_VEHICLE_NUM',
  OFFER_CONFIRM:         'OFFER_CONFIRM',

  // Find ride (browse all)
  FIND_ASK_REPEAT:     'FIND_ASK_REPEAT',
  FIND_ASK_PREFERENCE: 'FIND_ASK_PREFERENCE',
  FIND_ASK_LOCATION:   'FIND_ASK_LOCATION',
  FIND_ASK_DEST_LOC:   'FIND_ASK_DEST_LOC',
  FIND_BROWSE:         'FIND_BROWSE',
  FIND_RIDE_SELECTED:  'FIND_RIDE_SELECTED',

  // Booking
  BOOK_CONFIRM: 'BOOK_CONFIRM',

  // Recurring
  RECURRING_ASK: 'RECURRING_ASK',

  // My Bookings — passenger side
  CANCEL_SELECT: 'CANCEL_SELECT',
  CANCEL_CONFIRM: 'CANCEL_CONFIRM',

  // My Bookings — driver ride management
  RIDE_MANAGE: 'RIDE_MANAGE',
  RIDE_CANCEL_CONFIRM: 'RIDE_CANCEL_CONFIRM',
  RIDE_RESCHEDULE_TIME: 'RIDE_RESCHEDULE_TIME',

  // Rating
  RATING_ASK: 'RATING_ASK',
  RATING_FEEDBACK: 'RATING_FEEDBACK',

  // Post-trip re-route prompt
  POST_TRIP_ASK: 'POST_TRIP_ASK',

  // Feedback
  FEEDBACK_AWAIT: 'FEEDBACK_AWAIT',
};

const RIDE_PREFERENCE = {
  ALL: 'all',
  WOMEN_ONLY: 'women_only',
};

const GENDER = {
  MALE: 'Male',
  FEMALE: 'Female',
  OTHER: 'Other',
};

const VEHICLE_TYPES = ['car', 'bike'];

const RIDE_STATUS = {
  ACTIVE: 'active',
  FULL: 'full',
  CANCELLED: 'cancelled',
  COMPLETED: 'completed',
};

const BOOKING_STATUS = {
  CONFIRMED: 'confirmed',
  CANCELLED: 'cancelled',
};

const RESULTS_PAGE_SIZE = 3;
const SESSION_TTL_MS = 30 * 60 * 1000;
const MAX_PICKUP_RADIUS_KM = 3.0;
const MAX_DEST_RADIUS_KM   = 5.0;
const MAX_TIME_DIFF_MINUTES = 30;

module.exports = {
  FLOWS, STEPS, RIDE_PREFERENCE, GENDER,
  VEHICLE_TYPES, RIDE_STATUS, BOOKING_STATUS,
  RESULTS_PAGE_SIZE, SESSION_TTL_MS,
  MAX_PICKUP_RADIUS_KM, MAX_DEST_RADIUS_KM, MAX_TIME_DIFF_MINUTES,
};
